### ISSUE TITLE
Step 7 Rotation Check Issue? (Minor?)

### ISSUE THREAD

**Issue by aaron-sgy** [Frankushima/pete#14]
The third rotation is not detected with the given .txt sensor data?

**Comment by sophieqguan** [comment]
It does on mine? It's about 7 sec per rotation, ish. 

Also, I'm gonna have to update/replace the whole dummy .txt anyway so don't worry about the current version of sensor logic lol

**Comment by aaron-sgy** [comment]
sounds good :D
